import image2 from "../image/3.webp";

/**
 * Corps des articles — subtitle, author, blocs de contenu.
 * Métadonnées communes (titre, slug, date, image…) : `journalArticles.js`.
 * @typedef {{ subtitle: string, author: string, content: object[] }} ArticleBody
 */

/** @type {Record<string, ArticleBody>} */
export const JOURNAL_ARTICLE_BODIES = {
  "the-proust-project-how-scent-encodes-memory-forever": {
    subtitle:
      "The olfactory nerve connects directly to the amygdala — the seat of emotional memory — in 0.2 seconds.",
    author: "MADELEINE Editorial",
    content: [
      {
        type: "paragraph",
        text: "In 1913, when Marcel Proust published Swann's Way, he wasn't merely reaching for a poetic metaphor. By describing how the taste of a petite madeleine dipped in tea instantly resurrected the entire landscape of his childhood, he laid the foundation for a biological truth that science would take a century to map. What he named was not a simple recollection. It was a neurological collision—intimate proof that a single sensory imprint possesses the power to collapse twenty years of absence in a fraction of a second.",
      },
      {
        type: "paragraph",
        text: 'At MADELEINE, this intuition is more than an inspiration. It is our raison d\'être: to capture those rare human moments of such intensity that one finds themselves thinking: "I am experiencing something I refuse to forget."',
      },
      {
        type: "heading",
        level: 2,
        text: "The Anatomical Privilege of the Limbic System",
      },
      {
        type: "paragraph",
        text: "To understand why scent holds the keys to our most visceral emotions, one must look at the geography of the brain. Our senses do not travel at the same pace, nor by the same routes. Sight, hearing, touch, and taste are first filtered by the thalamus—the brain's grand cognitive relay station—before reaching our consciousness in a rationalized form.",
      },
      {
        type: "paragraph",
        text: "Olfaction, however, bypasses all customs.",
      },
      {
        type: "paragraph",
        text: "The olfactory nerve connects directly to the limbic system. In less than 0.2 seconds, the signal reaches the amygdala and the hippocampus—the absolute sanctuaries of emotional memory and long-term recall. There is no cognitive layer to sift the experience, no pre-constructed narrative to dull its impact. It is a raw, immediate dialogue.",
      },
      {
        type: "quote",
        text: "The olfactory bulb is an integral part of the limbic system, an area so closely tied to the genesis of emotion that it was once called the 'emotional brain'.",
        author: "Dr. Rachel Herz, Brown University",
      },
      {
        type: "paragraph",
        text: "This is why a scent does not merely remind you of a moment. It does not document it. It replays it in its original purity.",
      },
      {
        type: "heading",
        level: 2,
        text: "The Proustian Effect Put to the Test",
      },
      {
        type: "paragraph",
        text: "This magnetism of olfactory memory rests on three major empirical pillars, validated by the most rigorous research laboratories:",
      },
      {
        type: "heading",
        level: 3,
        text: "Pure Emotional Intensity",
      },
      {
        type: "paragraph",
        text: 'Research published in the academic journal Chemical Senses highlighted what scientists formally call the "Proustian Memory Effect." Their data proves that reminiscences triggered by scent possess an evocative charge and a personal significance infinitely denser than those generated by images or words. Where an image appeals to the intellect, a fragrance speaks to the body.',
      },
      {
        type: "heading",
        level: 3,
        text: "The Indelible Imprint",
      },
      {
        type: "paragraph",
        text: "For a long time, science believed humans were limited to perceiving 10,000 scents. A landmark study from Rockefeller University shattered this ceiling, revealing that our olfactory system can actually discriminate more than one trillion different stimuli. More crucially: a memory engraved under high emotional tension through the prism of scent proves almost entirely immune to the passage of time. While the brilliance of visual memories fades within months, the olfactory imprint remains intact, waiting in the shadows, ready to be reborn decades later.",
      },
      {
        type: "heading",
        level: 3,
        text: "The Clarity of the Initial Instant",
      },
      {
        type: "paragraph",
        text: "For a memory to be anchored forever, nature demands a very specific alignment of factors: the absolute novelty of the molecule, the intensity of an emotional state, and the singularity of a context. It is at this precise moment that encoding ceases to be passive and becomes an act of pure will.",
      },
      {
        type: "heading",
        level: 2,
        text: "The Resolution: From Nostalgia to Scent-Mapping",
      },
      {
        type: "paragraph",
        text: "Modernity has pushed us to delegate our lives to the retina and the screen. We accumulate digital snapshots, falsely believing that the sheer volume of pixels can arrest the flight of time. But an image freezes a scene and allows its breath to evaporate. Standing before a photograph of a cherished journey, we primarily measure an absence. The image cultivates the mourning of the moment; the fragrance, however, preserves its life.",
      },
      {
        type: "paragraph",
        text: "This is where photography ends and the Scent-Mapping protocol begins.",
      },
      {
        type: "quote",
        text: "Photography shows the past. Scent-Mapping allows you to re-inhabit it.",
        author: "MADELEINE",
      },
      {
        type: "paragraph",
        text: "By merging haute parfumerie with neuroscience, MADELEINE converts fragrance into an intimate technology. By introducing a virgin molecule at the zenith of your emotions—during a suspended journey or a shared moment of grace—we seal the experience.",
      },
      {
        type: "paragraph",
        text: "When, months or years later, the bottle is reopened in the privacy of your daily life, the illusion vanishes. Before the mind even attempts to analyze the top or base notes, the body remembers. The salt-crusted skin of a late afternoon on a forgotten island, the exact texture of the air, the precise quality of the attention you gave to another: it all returns, raw and lightning-fast.",
      },
      {
        type: "paragraph",
        text: "Bottling one's life is no longer a romantic wish. It is a sovereign ritual. The choice to refuse the wear and tear of time, and to finally hold the key to one's own eternity.",
      },
      {
        type: "signature",
        text: "MADELEINE — As it felt",
      },
    ],
  },
  "amalfi-coast-golden-hour-building-scent-from-a-coastline": {
    subtitle:
      "Sun-warmed lemon, wild rosemary, sea salt at dawn — coordinates, not decoration.",
    author: "MADELEINE Editorial",
    content: [
      {
        type: "paragraph",
        text: "A coastline is not a mood board. It is a set of coordinates — latitude, season, hour of light, the vegetation that grows in that specific salt wind. When MADELEINE composes from a journey, the destination is the brief. The formula is the map.",
      },
      {
        type: "heading",
        level: 2,
        text: "Geography as raw material",
      },
      {
        type: "paragraph",
        text: "The Amalfi Coast carries its own olfactory signature long before perfumery names it. The Sfusato Amalfitano — the coast's protected lemon — is not generic citrus: it is thick-skinned, high in essential oil, bred for terraced cliffs where the Tyrrhenian Sea reflects heat back into the groves. Wild rosemary and maquis herbs grow in the same stone seams. Sea spray leaves a mineral trace on skin at dawn that no studio accord can invent from scratch.",
      },
      {
        type: "paragraph",
        text: "Golden hour here is a collision of three temperatures: sun on lemon peel, cool shadow in cypress alleys, and the metallic snap of salt when the wind turns. Scent-Mapping does not quote those notes like a postcard. It traps the tension between them — so that years later, one inhalation restores the hour, not the cliché.",
      },
      {
        type: "heading",
        level: 2,
        text: "From itinerary to imprint",
      },
      {
        type: "paragraph",
        text: "Your questionnaire tells us where you are going and what you want to carry. We read region and season as compositional constraints — which botanicals belong to that shore, which emotional register matches the light you describe. The goal is alignment: an olfactory map that matches the emotional map of the trip.",
      },
      {
        type: "paragraph",
        text: "When geography and intention align, the memory does not flatten into anecdote. It stays dimensional — the way a place felt when you were inside it, not when you narrate it later. That is the difference between wearing a fragrance you already loved and commissioning one that exists only for this chapter.",
      },
      {
        type: "quote",
        text: "We do not choose a scent for its immediate appeal. We choose an imprint for its storage capacity.",
        author: "MADELEINE",
      },
      {
        type: "signature",
        text: "MADELEINE — As it felt",
      },
    ],
  },
  "why-smell-is-the-only-sense-that-bypasses-the-brains-filter": {
    subtitle: "Every other sense passes through the thalamus. Smell does not.",
    author: "MADELEINE Editorial",
    content: [
      {
        type: "paragraph",
        text: "Sight, sound, and touch share a gate. Smell does not. That anatomical exception is why MADELEINE trusts scent above the feed — and why a single breath can return you to a room you thought you had lost.",
      },
      {
        type: "heading",
        level: 2,
        text: "The thalamic relay — and the exception",
      },
      {
        type: "paragraph",
        text: "Most sensory signals pass through the thalamus before reaching conscious awareness. The thalamus prioritises, frames, and filters — a useful survival mechanism. Not every stimulus deserves a full emotional broadcast.",
      },
      {
        type: "paragraph",
        text: "Olfactory input is different. Neurons from the olfactory bulb project directly to the piriform cortex, amygdala, and hippocampus — structures central to emotion and episodic memory. There is no mandatory stop at the switchboard. The signal arrives with an immediacy other senses cannot match.",
      },
      {
        type: "heading",
        level: 2,
        text: "What the research shows",
      },
      {
        type: "paragraph",
        text: 'Peer-reviewed work on odour-evoked autobiographical memory — including studies by Chu and Downes and subsequent meta-analyses — consistently finds that smell-triggered recollections carry stronger emotional charge and sensory vividness than those cued by words or images. Researchers describe this as the formal "Proustian" effect: not nostalgia as story, but re-experiencing as sensation.',
      },
      {
        type: "paragraph",
        text: "Brain-imaging studies reinforce the mechanism. Odour cues activate the amygdala and hippocampal regions associated with emotional salience and memory encoding — often with less prefrontal mediation than visual cues. You do not debate a sudden smell; your body accepts it.",
      },
      {
        type: "heading",
        level: 2,
        text: "Why this matters for a bespoke formula",
      },
      {
        type: "paragraph",
        text: "For MADELEINE, this architecture is the product brief. We anchor threshold journeys — honeymoons, anniversaries, departures — in a fragrance worn only for that chapter. A dedicated scent creates a clean associative line: this molecule means this moment. The thalamus never gets the chance to sand it down.",
      },
      {
        type: "paragraph",
        text: "Photography curates the past into composition. Scent, handled with intention, can preserve the emotional truth of a day — not every detail, but the weight of being there. That is the filter we choose to bypass on purpose.",
      },
      {
        type: "signature",
        text: "MADELEINE — As it felt",
      },
    ],
  },
  "how-to-choose-the-perfume-for-your-honeymoon": {
    subtitle:
      "Not a guide to notes and accords. A guide to encoding the journey.",
    author: "MADELEINE Editorial",
    content: [
      {
        type: "paragraph",
        text: "This is not a guide on top notes or heart accords. It is a protocol for encoding. It is about ensuring your journey does not become a story you merely tell, but remains a moment you can forever feel.",
      },
      {
        type: "paragraph",
        text: "Most honeymoon fragrance advice starts with what you already like. For the purpose of memory, this is a technical error. What matters is the virgin molecule: a fragrance you have never worn, tied exclusively and eternally to the days you are currently living.",
      },
      {
        type: "heading",
        level: 2,
        text: "The MADELEINE Philosophy: The Scent as a Vessel",
      },
      {
        type: "paragraph",
        text: "At MADELEINE, we practice a radical inversion of luxury perfumery codes: This is the only perfume you buy before you have ever smelled it.",
      },
      {
        type: "paragraph",
        text: "Why? Because within The Proust Project, the fragrance is not the object of desire; it is the vehicle of the memory.",
      },
      {
        type: "paragraph",
        text: "We do not choose a scent for its immediate appeal.",
      },
      {
        type: "paragraph",
        text: "We choose an imprint for its storage capacity.",
      },
      {
        type: "paragraph",
        text: "Once ordered, there is no turning back. You will learn to love this fragrance not for its ingredients, but because it will become inseparable from the intensity of your union. The memory was never about the smell itself; it was always about what the smell would come to mean.",
      },
      {
        type: "heading",
        level: 2,
        text: "Your Destination is Our Brief",
      },
      {
        type: "paragraph",
        text: "We do not create based on your habitual tastes; we create based on the geography of your emotion. The landscape becomes the formula.",
      },
      {
        type: "paragraph",
        text: "A honeymoon on the Amalfi Coast? A milestone anniversary in Kyoto? A night in Marrakech that refused to end?",
      },
      {
        type: "paragraph",
        text: "When you share your itinerary with us, we begin distilling the raw materials of that specific region, that specific season, and that specific emotional intention. We ask. We listen. We distill.",
      },
      {
        type: "heading",
        level: 2,
        text: "The Imprinting Protocol",
      },
      {
        type: "paragraph",
        text: "The more foreign the fragrance is to your past, the cleaner the imprint will be.",
      },
      {
        type: "paragraph",
        text: "Immersion: Wear it every single day of the journey. Let it saturate your skin, your linens, and the very air you breathe together.",
      },
      {
        type: "paragraph",
        text: "The Seal: Upon your return, close the bottle. Reserve it. The honeymoon ends; the anchor does not.",
      },
      {
        type: "paragraph",
        text: "Reactivation: Later, when life crowds in and the details begin to blur, you will not have to chase the memory. You will simply breathe it.",
      },
      {
        type: "paragraph",
        text: "This is not mere romance. It is sensory technology. Closing the bottle is an act of closing a chapter to protect it from the wear and tear of time. What we build for you is not a fashion accessory; it is a living archive.",
      },
      {
        type: "paragraph",
        text: "Choose the moment. We create the imprint.",
      },
      {
        type: "signature",
        text: "MADELEINE — As it felt",
      },
    ],
  },
  "why-we-always-wanted-to-bottle-our-memories": {
    subtitle:
      "I once looked at a photo of a trip I loved and felt absolutely nothing.",
    author: "MADELEINE Editorial",
    content: [
      {
        type: "quote",
        text: "Nothing brings to life again a forgotten memory like fragrance.",
        author: "Christopher Poindexter",
        isOpening: true,
      },
      {
        type: "video",
        src: "https://youtu.be/rydKd5BUBsI",
        quote:
          "I wish there could be an invention that bottled up memories like perfume.",
        author: "Daphne du Maurier, Rebecca",
        poster: image2,
        isYouTube: true,
      },
      {
        type: "paragraph",
        text: "Long perceived as a romantic reverie, this sentence—uttered in Rebecca by Daphne du Maurier—reveals today an intuition of a troubling accuracy. It speaks neither of nostalgia nor of conservation. It formulates a much more precise desire: that of reliving the moment in its original purity, rather than cultivating its mourning.",
      },
      {
        type: "paragraph",
        text: "For decades, modernity believed that the image alone would fulfill this function. We delegated our memory to the retina and the lens, accumulating evidence as if the quantity of pixels could compensate for the loss of emotional density and archive what we called memories.",
      },
      {
        type: "paragraph",
        text: "And yet, something resisted…",
      },
      {
        type: "paragraph",
        text: "Images preserved the forms, but allowed the breath to evaporate. By freezing the scene, the texture was lost. Facing a photo of a beloved trip, it is rarely the moment that returns to us, but its melancholy: we no longer feel the instant; we only measure its absence. As if memory had accepted to be shown, but refused to be fully transmitted.",
      },
      {
        type: "paragraph",
        text: "Memory was never designed to be purely visual. It lacked an element capable of speaking directly to the body. This is where photography stops and Scent-Mapping begins.",
      },
      {
        type: "paragraph",
        text: "This gesture transforms scent into an intimate technology. It is no longer about documenting a moment, but about how to seal it. The goal is not to remember time, but to prevent it from wearing out.",
      },
      {
        type: "paragraph",
        text: "Sophisticated travelers practice what insiders call Memory Anchoring. The protocol is of a disarming simplicity:",
      },
      {
        type: "heading",
        text: "The virgin molecule",
        level: 3,
      },
      {
        type: "paragraph",
        text: "A unique fragrance is chosen—unknown, never worn before, devoid of any past.",
      },
      {
        type: "heading",
        text: "Imprinting",
        level: 3,
      },
      {
        type: "paragraph",
        text: "Throughout the journey, it becomes the only admitted olfactory footprint. No other perfume, no interference.",
      },
      {
        type: "heading",
        text: "The sillage",
        level: 3,
      },
      {
        type: "paragraph",
        text: "The scent accompanies every moment without being noticed, slowly soaking into the body, the silk of the clothes, the very air of the days.",
      },
      {
        type: "paragraph",
        text: "Upon return, the bottle is closed. It is no longer worn in public. It exits the circuit of the everyday. It ceases to be an object and becomes a ritual.",
      },
      {
        type: "paragraph",
        text: "Months, sometimes years later, in those blurred moments where life has thickened, where time has smoothed out the emotions. A single breath is enough. The effect is immediate, and always the same. Even before the mind can analyze the top or base notes, the body recognizes.",
      },
      {
        type: "paragraph",
        text: "Tenderness returns, raw, without the effort of thought. The salt-crusted skin of an evening on a silent island. The particular quality of the attention we gave to one another. Scent does not trigger a memory in a narrative sense; it projects us back into it.",
      },
      {
        type: "paragraph",
        text: 'What we feel then is not nostalgia, but an impression of a "first time" rediscovered. Time ceases to pass. The emotion was never dulled; it was simply put on hold, preserved from the wear and tear of the gaze.',
      },
      {
        type: "paragraph",
        text: "Thus, scent-mapping does not seek to archive the past but to re-inhabit it. It finally answers that ancient desire formulated in Rebecca: no longer merely to preserve memory as a visible object, but to keep it as a living experience.",
      },
      {
        type: "paragraph",
        text: "It is in this space—invisible, silent, profoundly intimate—that MADELEINE carves its vision: That of dethroning the image in favor of sensation, and finally putting our memories into a bottle.",
      },
      {
        type: "signature",
        text: "MADELEINE — As it felt",
      },
    ],
  },
};
