import { useState, useEffect } from "react";
import { Link, useParams, useNavigate, useLocation } from "react-router-dom";
import image2 from "../image/3.png";
import lemonPerfumeImage from "../image/lemon+perfume.png";
import memoriesImage from "../image/memories.png";
import SiteFooter from "../components/layout/SiteFooter";
import SyncPageSeo from "../components/seo/SyncPageSeo";
import { BrandMark, typewriterFaceClass } from "../components/typography";
import {
  ARTICLE_SEO_BY_SLUG,
  PROUST_ARTICLE_SLUG,
  absoluteUrl,
  getArticlePath,
} from "../config/seoMeta";

// Données d'exemple pour les articles
const articles = {
  "the-proust-project-how-scent-encodes-memory-forever": {
    id: "the-proust-project-how-scent-encodes-memory-forever",
    title: "The Proust Project: How Scent Encodes Memory Forever",
    subtitle:
      "The olfactory nerve connects directly to the amygdala — the seat of emotional memory — in 0.2 seconds.",
    author: "Scentience Editorial",
    date: "April 2026",
    category: "Science",
    heroImage: memoriesImage,
    excerpt:
      "From Swann's Way to the limbic system: why a scent does not document a moment—it replays it in its original purity.",
    content: [
      {
        type: "paragraph",
        text: "In 1913, when Marcel Proust published Swann's Way, he wasn't merely reaching for a poetic metaphor. By describing how the taste of a petite madeleine dipped in tea instantly resurrected the entire landscape of his childhood, he laid the foundation for a biological truth that science would take a century to map. What he named was not a simple recollection. It was a neurological collision—intimate proof that a single sensory imprint possesses the power to collapse twenty years of absence in a fraction of a second.",
      },
      {
        type: "paragraph",
        text: 'At Scentience, this intuition is more than an inspiration. It is our raison d\'être: to capture those rare human moments of such intensity that one finds themselves thinking: "I am experiencing something I refuse to forget."',
      },
      {
        type: "heading",
        level: 2,
        text: "The Anatomical Privilege of the Limbic System",
      },
      {
        type: "paragraph",
        text: "To understand why scent holds the keys to our most visceral emotions, one must look at the geography of the brain. Our senses do not travel at the same pace, nor by the same routes. Sight, hearing, touch, and taste are first filtered by the thalamus—the brain's grand cognitive relay station—before reaching our consciousness in a rationalized form.",
      },
      {
        type: "paragraph",
        text: "Olfaction, however, bypasses all customs.",
      },
      {
        type: "paragraph",
        text: "The olfactory nerve connects directly to the limbic system. In less than 0.2 seconds, the signal reaches the amygdala and the hippocampus—the absolute sanctuaries of emotional memory and long-term recall. There is no cognitive layer to sift the experience, no pre-constructed narrative to dull its impact. It is a raw, immediate dialogue.",
      },
      {
        type: "quote",
        text: "The olfactory bulb is an integral part of the limbic system, an area so closely tied to the genesis of emotion that it was once called the 'emotional brain'.",
        author: "Dr. Rachel Herz, Brown University",
      },
      {
        type: "paragraph",
        text: "This is why a scent does not merely remind you of a moment. It does not document it. It replays it in its original purity.",
      },
      {
        type: "heading",
        level: 2,
        text: "The Proustian Effect Put to the Test",
      },
      {
        type: "paragraph",
        text: "This magnetism of olfactory memory rests on three major empirical pillars, validated by the most rigorous research laboratories:",
      },
      {
        type: "heading",
        level: 3,
        text: "Pure Emotional Intensity",
      },
      {
        type: "paragraph",
        text: 'Research published in the academic journal Chemical Senses highlighted what scientists formally call the "Proustian Memory Effect." Their data proves that reminiscences triggered by scent possess an evocative charge and a personal significance infinitely denser than those generated by images or words. Where an image appeals to the intellect, a fragrance speaks to the body.',
      },
      {
        type: "heading",
        level: 3,
        text: "The Indelible Imprint",
      },
      {
        type: "paragraph",
        text: "For a long time, science believed humans were limited to perceiving 10,000 scents. A landmark study from Rockefeller University shattered this ceiling, revealing that our olfactory system can actually discriminate more than one trillion different stimuli. More crucially: a memory engraved under high emotional tension through the prism of scent proves almost entirely immune to the passage of time. While the brilliance of visual memories fades within months, the olfactory imprint remains intact, waiting in the shadows, ready to be reborn decades later.",
      },
      {
        type: "heading",
        level: 3,
        text: "The Clarity of the Initial Instant",
      },
      {
        type: "paragraph",
        text: "For a memory to be anchored forever, nature demands a very specific alignment of factors: the absolute novelty of the molecule, the intensity of an emotional state, and the singularity of a context. It is at this precise moment that encoding ceases to be passive and becomes an act of pure will.",
      },
      {
        type: "heading",
        level: 2,
        text: "The Resolution: From Nostalgia to Scent-Mapping",
      },
      {
        type: "paragraph",
        text: "Modernity has pushed us to delegate our lives to the retina and the screen. We accumulate digital snapshots, falsely believing that the sheer volume of pixels can arrest the flight of time. But an image freezes a scene and allows its breath to evaporate. Standing before a photograph of a cherished journey, we primarily measure an absence. The image cultivates the mourning of the moment; the fragrance, however, preserves its life.",
      },
      {
        type: "paragraph",
        text: "This is where photography ends and the Scent-Mapping protocol begins.",
      },
      {
        type: "quote",
        text: "Photography shows the past. Scent-Mapping allows you to re-inhabit it.",
        author: "Scentience",
      },
      {
        type: "paragraph",
        text: "By merging haute parfumerie with neuroscience, Scentience converts fragrance into an intimate technology. By introducing a virgin molecule at the zenith of your emotions—during a suspended journey or a shared moment of grace—we seal the experience.",
      },
      {
        type: "paragraph",
        text: "When, months or years later, the bottle is reopened in the privacy of your daily life, the illusion vanishes. Before the mind even attempts to analyze the top or base notes, the body remembers. The salt-crusted skin of a late afternoon on a forgotten island, the exact texture of the air, the precise quality of the attention you gave to another: it all returns, raw and lightning-fast.",
      },
      {
        type: "paragraph",
        text: "Bottling one's life is no longer a romantic wish. It is a sovereign ritual. The choice to refuse the wear and tear of time, and to finally hold the key to one's own eternity.",
      },
      {
        type: "signature",
        text: "Scentience — As it felt",
      },
    ],
  },
  "amalfi-coast-golden-hour-building-scent-from-a-coastline": {
    id: "amalfi-coast-golden-hour-building-scent-from-a-coastline",
    title: "The Amalfi Coast at Golden Hour: Building a Scent from a Coastline",
    subtitle:
      "Sun-warmed lemon, wild rosemary, sea salt at dawn — coordinates, not decoration.",
    author: "Scentience Editorial",
    date: "April 2026",
    category: "Journal",
    heroImage: lemonPerfumeImage,
    excerpt:
      "How the raw materials of a specific place become the olfactory coordinates of a memory that will last a lifetime.",
    content: [
      {
        type: "paragraph",
        text: "Sun-warmed lemon, wild rosemary, the metallic snap of sea salt at dawn: a coastline is not a mood board. It is a set of coordinates. When Scentience builds a formula from a journey, we treat destination as brief — region, season, light, what you refuse to forget.",
      },
      {
        type: "paragraph",
        text: "Golden hour on the Amalfi coast is a collision of heat, vegetation, and mineral water. The goal is not to quote those notes like a postcard; it is to trap the tension between them so that, years later, one breath restores the hour, not the cliché.",
      },
      {
        type: "paragraph",
        text: "That is why the raw materials matter as geography, not as fashion. The olfactory map has to match the emotional map. When they align, the memory does not fade into anecdote — it stays dimensional.",
      },
      {
        type: "signature",
        text: "Scentience — As it felt",
      },
    ],
  },
  "why-smell-is-the-only-sense-that-bypasses-the-brains-filter": {
    id: "why-smell-is-the-only-sense-that-bypasses-the-brains-filter",
    title: "Why Smell Is the Only Sense That Bypasses the Brain's Filter",
    subtitle: "Every other sense passes through the thalamus. Smell does not.",
    author: "Scentience Editorial",
    date: "April 2026",
    category: "Science",
    heroImage: lemonPerfumeImage,
    excerpt:
      "Here is what that means for emotional memory — and for why Scentience trusts scent above the feed.",
    content: [
      {
        type: "paragraph",
        text: "Every other sense passes through the thalamus — the brain's switchboard — where inputs are gated, prioritized, and framed before they reach the cortex. It is a useful filter for survival: not everything deserves a full emotional broadcast.",
      },
      {
        type: "paragraph",
        text: 'Olfaction is the exception. Signals from the nose reach the amygdala and hippocampus with a directness that explains the uncanny "I was there" quality of a sudden smell. You do not debate it; your body accepts it.',
      },
      {
        type: "paragraph",
        text: "For Scentience, that architecture is not trivia. It is the reason we anchor honeymoons, anniversaries, and threshold moments in a unique formula worn only for that chapter. The thalamus cannot sand down what never passed through it.",
      },
      {
        type: "paragraph",
        text: "Images curate. Scent, handled with intention, can preserve — not every detail, but the emotional truth of a day. That is the filter we choose to bypass on purpose.",
      },
      {
        type: "signature",
        text: "Scentience — As it felt",
      },
    ],
  },
  "how-to-choose-the-perfume-for-your-honeymoon": {
    id: "how-to-choose-the-perfume-for-your-honeymoon",
    title: "How to Choose the Perfume for Your Honeymoon",
    subtitle:
      "Not a guide to notes and accords. A guide to encoding the journey.",
    author: "Scentience Editorial",
    date: "April 2026",
    category: "Journal",
    heroImage: lemonPerfumeImage,
    excerpt:
      "Before the trip becomes a story you tell instead of a moment you feel.",
    content: [
      {
        type: "paragraph",
        text: "This is not a guide on top notes or heart accords. It is a protocol for encoding. It is about ensuring your journey does not become a story you merely tell, but remains a moment you can forever feel.",
      },
      {
        type: "paragraph",
        text: "Most honeymoon fragrance advice starts with what you already like. For the purpose of memory, this is a technical error. What matters is the virgin molecule: a fragrance you have never worn, tied exclusively and eternally to the days you are currently living.",
      },
      {
        type: "heading",
        level: 2,
        text: "The Scentience Philosophy: The Scent as a Vessel",
      },
      {
        type: "paragraph",
        text: "At Scentience, we practice a radical inversion of luxury perfumery codes: This is the only perfume you buy before you have ever smelled it.",
      },
      {
        type: "paragraph",
        text: "Why? Because within The Proust Project, the fragrance is not the object of desire; it is the vehicle of the memory.",
      },
      {
        type: "paragraph",
        text: "We do not choose a scent for its immediate appeal.",
      },
      {
        type: "paragraph",
        text: "We choose an imprint for its storage capacity.",
      },
      {
        type: "paragraph",
        text: "Once ordered, there is no turning back. You will learn to love this fragrance not for its ingredients, but because it will become inseparable from the intensity of your union. The memory was never about the smell itself; it was always about what the smell would come to mean.",
      },
      {
        type: "heading",
        level: 2,
        text: "Your Destination is Our Brief",
      },
      {
        type: "paragraph",
        text: "We do not create based on your habitual tastes; we create based on the geography of your emotion. The landscape becomes the formula.",
      },
      {
        type: "paragraph",
        text: "A honeymoon on the Amalfi Coast? A milestone anniversary in Kyoto? A night in Marrakech that refused to end?",
      },
      {
        type: "paragraph",
        text: "When you share your itinerary with us, we begin distilling the raw materials of that specific region, that specific season, and that specific emotional intention. We ask. We listen. We distill.",
      },
      {
        type: "heading",
        level: 2,
        text: "The Imprinting Protocol",
      },
      {
        type: "paragraph",
        text: "The more foreign the fragrance is to your past, the cleaner the imprint will be.",
      },
      {
        type: "paragraph",
        text: "Immersion: Wear it every single day of the journey. Let it saturate your skin, your linens, and the very air you breathe together.",
      },
      {
        type: "paragraph",
        text: "The Seal: Upon your return, close the bottle. Reserve it. The honeymoon ends; the anchor does not.",
      },
      {
        type: "paragraph",
        text: "Reactivation: Later, when life crowds in and the details begin to blur, you will not have to chase the memory. You will simply breathe it.",
      },
      {
        type: "paragraph",
        text: "This is not mere romance. It is sensory technology. Closing the bottle is an act of closing a chapter to protect it from the wear and tear of time. What we build for you is not a fashion accessory; it is a living archive.",
      },
      {
        type: "paragraph",
        text: "Choose the moment. We create the imprint.",
      },
      {
        type: "signature",
        text: "Scentience — As it felt",
      },
    ],
  },
  "why-we-always-wanted-to-bottle-our-memories": {
    id: "why-we-always-wanted-to-bottle-our-memories",
    title: "Why we always wanted to bottle our memories",
    subtitle:
      "I once looked at a photo of a trip I loved and felt absolutely nothing.",
    author: "Scentience Editorial",
    date: "February 12, 2026",
    category: "Editorial",
    heroImage: memoriesImage,
    excerpt:
      "Why photography stops where scent-mapping begins — and what Rebecca already knew about bottling the instant.",
    content: [
      {
        type: "quote",
        text: "Nothing brings to life again a forgotten memory like fragrance.",
        author: "Christopher Poindexter",
        isOpening: true,
      },
      {
        type: "video",
        src: "https://youtu.be/rydKd5BUBsI", // URL YouTube
        quote:
          "I wish there could be an invention that bottled up memories like perfume.",
        author: "Daphne du Maurier, Rebecca",
        poster: image2, // Image de prévisualisation
        isYouTube: true,
      },
      {
        type: "paragraph",
        text: "Long perceived as a romantic reverie, this sentence—uttered in Rebecca by Daphne du Maurier—reveals today an intuition of a troubling accuracy. It speaks neither of nostalgia nor of conservation. It formulates a much more precise desire: that of reliving the moment in its original purity, rather than cultivating its mourning.",
      },

      {
        type: "paragraph",
        text: "For decades, modernity believed that the image alone would fulfill this function. We delegated our memory to the retina and the lens, accumulating evidence as if the quantity of pixels could compensate for the loss of emotional density and archive what we called memories.",
      },
      {
        type: "paragraph",
        text: "And yet, something resisted…",
      },
      {
        type: "paragraph",
        text: "Images preserved the forms, but allowed the breath to evaporate. By freezing the scene, the texture was lost. Facing a photo of a beloved trip, it is rarely the moment that returns to us, but its melancholy: we no longer feel the instant; we only measure its absence. As if memory had accepted to be shown, but refused to be fully transmitted.",
      },
      {
        type: "paragraph",
        text: "Memory was never designed to be purely visual. It lacked an element capable of speaking directly to the body. This is where photography stops and Scent-Mapping begins.",
      },
      {
        type: "paragraph",
        text: "This gesture transforms scent into an intimate technology. It is no longer about documenting a moment, but about how to seal it. The goal is not to remember time, but to prevent it from wearing out.",
      },
      {
        type: "paragraph",
        text: "Sophisticated travelers practice what insiders call Memory Anchoring. The protocol is of a disarming simplicity:",
      },
      {
        type: "heading",
        text: "The virgin molecule",
        level: 3,
      },
      {
        type: "paragraph",
        text: "A unique fragrance is chosen—unknown, never worn before, devoid of any past.",
      },
      {
        type: "heading",
        text: "Imprinting",
        level: 3,
      },
      {
        type: "paragraph",
        text: "Throughout the journey, it becomes the only admitted olfactory footprint. No other perfume, no interference.",
      },
      {
        type: "heading",
        text: "The sillage",
        level: 3,
      },
      {
        type: "paragraph",
        text: "The scent accompanies every moment without being noticed, slowly soaking into the body, the silk of the clothes, the very air of the days.",
      },
      {
        type: "paragraph",
        text: "Upon return, the bottle is closed. It is no longer worn in public. It exits the circuit of the everyday. It ceases to be an object and becomes a ritual.",
      },
      {
        type: "paragraph",
        text: "Months, sometimes years later, in those blurred moments where life has thickened, where time has smoothed out the emotions. A single breath is enough. The effect is immediate, and always the same. Even before the mind can analyze the top or base notes, the body recognizes.",
      },
      {
        type: "paragraph",
        text: "Tenderness returns, raw, without the effort of thought. The salt-crusted skin of an evening on a silent island. The particular quality of the attention we gave to one another. Scent does not trigger a memory in a narrative sense; it projects us back into it.",
      },
      {
        type: "paragraph",
        text: 'What we feel then is not nostalgia, but an impression of a "first time" rediscovered. Time ceases to pass. The emotion was never dulled; it was simply put on hold, preserved from the wear and tear of the gaze.',
      },
      {
        type: "paragraph",
        text: "Thus, scent-mapping does not seek to archive the past but to re-inhabit it. It finally answers that ancient desire formulated in Rebecca: no longer merely to preserve memory as a visible object, but to keep it as a living experience.",
      },
      {
        type: "paragraph",
        text: "It is in this space—invisible, silent, profoundly intimate—that Scentience carves its vision: That of dethroning the image in favor of sensation, and finally putting our memories into a bottle.",
      },
      {
        type: "signature",
        text: "Scentience — As it felt",
      },
    ],
  },
};

export default function ArticlePage() {
  const { slug: slugFromRoute } = useParams();
  const location = useLocation();
  const pathname = location.pathname.replace(/\/$/, "") || "/";

  const slug =
    slugFromRoute ??
    (pathname === "/journal/the-proust-project"
      ? PROUST_ARTICLE_SLUG
      : undefined);

  const navigate = useNavigate();
  const [article, setArticle] = useState(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setIsLoading(true);
    const timer = window.setTimeout(() => {
      if (!slug) {
        setArticle(null);
        setIsLoading(false);
        return;
      }
      const foundArticle = articles[slug];
      if (foundArticle) {
        setArticle(foundArticle);
      } else {
        setArticle(null);
      }
      setIsLoading(false);
    }, 300);
    return () => window.clearTimeout(timer);
  }, [slug]);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-paper flex items-center justify-center">
        <div className="text-mist font-light">Loading...</div>
      </div>
    );
  }

  if (!article) {
    return (
      <div className="min-h-screen bg-paper flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-2xl typo-title italic mb-4">Article not found</h1>
          <button
            onClick={() => navigate("/")}
            className="text-sm text-mist hover:text-ink underline underline-offset-4"
          >
            Return to home
          </button>
        </div>
      </div>
    );
  }

  const seo = ARTICLE_SEO_BY_SLUG[article.id];
  const canonicalUrl = absoluteUrl(
    seo?.canonicalPath ?? getArticlePath(article.id),
  );
  const pageTitle = seo?.title ?? `${article.title} | Scentience`;
  const description =
    seo?.description ?? article.excerpt ?? article.subtitle ?? "";
  const keywords = seo?.keywords;
  const ogType = seo?.ogType ?? "article";

  return (
    <div className="min-h-screen bg-paper">
      <SyncPageSeo
        title={pageTitle}
        description={description}
        keywords={keywords}
        canonicalUrl={canonicalUrl}
        ogType={ogType}
      />
      {/* Header */}
      <Header navigate={navigate} />

      {/* Hero Section - Ultra Luxueux */}
      <section className="relative w-full h-[36vh] min-h-[300px] max-h-[300px] overflow-hidden pt-16">
        <div className="absolute inset-0">
          <img
            src={article.heroImage}
            alt={article.title}
            className="w-full h-full object-cover object-center"
          />
          {/* Overlay élégant avec gradient raffiné */}
          <div className="absolute inset-0 bg-gradient-to-b from-black/25 via-black/15 to-black/45" />
          {/* Vignette subtile pour effet cinématographique */}
          <div className="absolute inset-0 bg-gradient-radial from-transparent via-transparent to-black/25" />
          {/* Bordure subtile en bas */}
          <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
        </div>
        <div className="relative z-10 h-full flex items-end">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full pb-10 sm:pb-14">
            <div className="max-w-3xl">
              <div className="mb-2.5">
                <span className="text-[10px] sm:text-xs typo-subtitle text-white/60 font-light">
                  {article.category}
                </span>
              </div>
              <h2 className="typo-title max-w-3xl text-lg leading-snug sm:text-xl lg:text-2xl xl:text-3xl mb-3 text-wine [text-shadow:0_2px_12px_rgba(0,0,0,0.55)]">
                {article.title}
              </h2>
              <p className="typo-body-lead max-w-2xl text-paper/95 normal-case">
                {article.subtitle}
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Article Content */}
      <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 ">
        {/* Article Meta */}
        <div className="mb-8 pb-4 border-b border-ink/20">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
            <div>
              <p className="text-sm text-ink/70 font-light">
                By <span className="text-ink">{article.author}</span>
              </p>
            </div>
            <div>
              <p className="text-sm text-ink/70 font-light">{article.date}</p>
            </div>
          </div>
        </div>

        {/* Excerpt - Only show if exists */}
        {article.excerpt && (
          <div className="mb-12 pb-6 border-b border-ink/10">
            <p className="typo-body-lead max-w-3xl italic text-ink/85">
              {article.excerpt}
            </p>
          </div>
        )}

        {/* Article Body */}
        <div className="prose prose-lg max-w-none mt-8">
          {article.content.map((block, index) => {
            if (block.type === "paragraph") {
              // Détecter si c'est le premier paragraphe après une citation ou vidéo
              const prevBlock = index > 0 ? article.content[index - 1] : null;
              const isFirstParagraph =
                index === 0 ||
                (prevBlock &&
                  (prevBlock.type === "quote" || prevBlock.type === "video"));

              return (
                <p
                  key={index}
                  className={`text-sm sm:text-base text-ink/70 leading-[1.85] font-light ${
                    isFirstParagraph ? "mb-10 first-paragraph" : "mb-7"
                  }`}
                  style={{
                    letterSpacing: "0.015em",
                  }}
                >
                  {isFirstParagraph && (
                    <span
                      className="float-left text-5xl sm:text-6xl typo-title leading-[0.85] mr-2 mt-1 font-light"
                      style={{
                        fontFamily: "Canela, Cormorant Garamond, serif",
                      }}
                    >
                      {block.text.charAt(0)}
                    </span>
                  )}
                  <span className={isFirstParagraph ? "block" : ""}>
                    {isFirstParagraph ? block.text.slice(1).trim() : block.text}
                  </span>
                </p>
              );
            }
            if (block.type === "quote") {
              // Opening quote with special styling
              if (block.isOpening) {
                return (
                  <blockquote key={index} className="my-6 py-4 text-center">
                    <div className="max-w-3xl mx-auto">
                      <p className="text-xl sm:text-2xl lg:text-3xl typo-title italic leading-relaxed mb-2 font-light">
                        "{block.text}"
                      </p>
                      <p className="text-xs text-mist font-light tracking-wide">
                        — {block.author}
                      </p>
                    </div>
                  </blockquote>
                );
              }
              // Regular quote
              return (
                <blockquote
                  key={index}
                  className="border-l-4 border-mist/50 pl-8 py-6 my-12"
                >
                  <p className="text-xl sm:text-2xl typo-title italic leading-relaxed mb-4 font-light">
                    "{block.text}"
                  </p>
                  <p className="text-sm text-mist font-light">
                    — {block.author}
                  </p>
                </blockquote>
              );
            }
            if (block.type === "heading") {
              const level = block.level || 3;
              const HeadingTag = level === 2 ? "h2" : level === 3 ? "h3" : "h4";
              const Component = HeadingTag;
              return (
                <Component
                  key={index}
                  className="text-xl sm:text-2xl typo-title font-light mt-12 mb-6"
                >
                  {block.text}
                </Component>
              );
            }
            if (block.type === "signature") {
              return (
                <div key={index} className="mt-16 pt-8 border-t border-ink/20">
                  <p className="text-lg sm:text-xl typo-title italic font-light text-right">
                    {block.text}
                  </p>
                </div>
              );
            }
            if (block.type === "image") {
              return (
                <figure key={index} className="my-16">
                  <div className="aspect-[16/10] overflow-hidden mb-4">
                    <img
                      src={block.src}
                      alt={block.caption || ""}
                      className="w-full h-full object-cover"
                    />
                  </div>
                  {block.caption && (
                    <figcaption className="text-sm text-mist font-light italic text-center">
                      {block.caption}
                    </figcaption>
                  )}
                </figure>
              );
            }
            if (block.type === "video") {
              // Convertir l'URL YouTube en format embed si nécessaire
              const getYouTubeEmbedUrl = (url) => {
                if (!url) return null;
                if (url.includes("youtube.com/embed/")) return url;
                if (url.includes("youtu.be/")) {
                  const videoId = url.split("youtu.be/")[1]?.split("?")[0];
                  return videoId
                    ? `https://www.youtube.com/embed/${videoId}`
                    : null;
                }
                if (url.includes("youtube.com/watch?v=")) {
                  const videoId = url.split("watch?v=")[1]?.split("&")[0];
                  return videoId
                    ? `https://www.youtube.com/embed/${videoId}`
                    : null;
                }
                return null;
              };

              const youtubeEmbedUrl = getYouTubeEmbedUrl(block.src);

              return (
                <figure key={index} className="my-24 -mx-4 sm:-mx-8 lg:-mx-16">
                  <div className="relative aspect-[16/9] overflow-hidden bg-black group">
                    {/* Bordure élégante */}
                    <div className="absolute inset-0 border border-white/10 z-10 pointer-events-none" />
                    <div className="absolute inset-[1px] border border-black/20 z-10 pointer-events-none" />

                    {youtubeEmbedUrl ? (
                      <div className="relative w-full h-full">
                        <iframe
                          src={`${youtubeEmbedUrl}?modestbranding=1&rel=0&showinfo=0`}
                          className="w-full h-full"
                          frameBorder="0"
                          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                          allowFullScreen
                          title={block.quote || "Video"}
                        />
                        {/* Overlay subtil au hover pour effet luxueux */}
                        <div className="absolute inset-0 bg-gradient-to-t from-black/0 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none z-20" />
                        {/* Vignette subtile */}
                        <div className="absolute inset-0 bg-gradient-radial from-transparent via-transparent to-black/10 pointer-events-none z-20" />
                      </div>
                    ) : block.src ? (
                      <video
                        className="w-full h-full object-cover"
                        poster={block.poster}
                        controls
                        playsInline
                      >
                        <source src={block.src} type="video/mp4" />
                        Your browser does not support the video tag.
                      </video>
                    ) : (
                      <div className="relative w-full h-full flex items-center justify-center">
                        <img
                          src={block.poster}
                          alt="Video placeholder"
                          className="w-full h-full object-cover opacity-50"
                        />
                        {/* Overlay avec gradient élégant */}
                        <div className="absolute inset-0 bg-gradient-to-b from-black/60 via-black/50 to-black/70 flex items-center justify-center">
                          <div className="text-center px-6 sm:px-8 lg:px-12 max-w-4xl z-10">
                            {/* Icône play stylisée */}
                            <div className="mb-8 flex justify-center">
                              <div className="relative">
                                <div className="absolute inset-0 bg-white/20 rounded-full blur-xl"></div>
                                <div className="relative w-20 h-20 sm:w-24 sm:h-24 bg-white/10 backdrop-blur-sm rounded-full flex items-center justify-center border border-white/20">
                                  <svg
                                    className="w-8 h-8 sm:w-10 sm:h-10 text-white ml-1"
                                    fill="currentColor"
                                    viewBox="0 0 24 24"
                                  >
                                    <path d="M8 5v14l11-7z" />
                                  </svg>
                                </div>
                              </div>
                            </div>
                            {/* Citation élégante */}
                            <blockquote className="space-y-4">
                              <p className="text-2xl sm:text-3xl lg:text-4xl xl:text-5xl typo-title italic text-white leading-relaxed font-light">
                                "{block.quote}"
                              </p>
                              <p className="text-sm sm:text-base text-white/80 font-light tracking-wide">
                                — {block.author}
                              </p>
                            </blockquote>
                          </div>
                        </div>
                        {/* Grain de film pour effet cinématographique */}
                        <div
                          className="absolute inset-0 opacity-[0.02] pointer-events-none"
                          style={{
                            backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 400 400' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noiseFilter'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noiseFilter)'/%3E%3C/svg%3E")`,
                          }}
                        />
                      </div>
                    )}
                  </div>
                  {/* Citation élégante sous la vidéo YouTube */}
                  {youtubeEmbedUrl && block.quote && (
                    <div className="mt-10 px-4 sm:px-8 text-center">
                      <blockquote className="max-w-3xl mx-auto">
                        <p className="text-lg sm:text-xl typo-title italic leading-relaxed mb-3 font-light">
                          "{block.quote}"
                        </p>
                        <p className="text-xs sm:text-sm text-mist font-light tracking-wide">
                          — {block.author}
                        </p>
                      </blockquote>
                    </div>
                  )}
                  {block.caption && !youtubeEmbedUrl && (
                    <figcaption className="text-sm text-mist font-light italic text-center mt-6 px-4">
                      {block.caption}
                    </figcaption>
                  )}
                </figure>
              );
            }
            return null;
          })}
        </div>

        {/* CTA — bande wine, pleine largeur */}
        <div
          className="relative left-1/2 mt-24 w-screen max-w-none -translate-x-1/2 overflow-hidden bg-wine px-6 py-16 sm:mt-32 sm:px-8 sm:py-20 lg:px-12"
          aria-labelledby="article-cta-heading"
        >
          <div
            className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/[0.08] via-transparent to-black/[0.16]"
            aria-hidden
          />
          <div
            className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-paper/30 to-transparent"
            aria-hidden
          />
          <div
            className="pointer-events-none absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-paper/18 to-transparent"
            aria-hidden
          />

          <div className="relative mx-auto max-w-3xl text-center">
            <p className="font-subtitle text-[10px] uppercase tracking-[0.22em] text-paper/50">
              Before it lives only in photographs
            </p>
            <h2
              id="article-cta-heading"
              className={`${typewriterFaceClass} mt-5 text-2xl font-normal normal-case leading-[1.2] text-paper sm:text-3xl sm:leading-tight`}
            >
              Give your next memory a scent only you can reopen.
            </h2>
            <p className="typo-typewriter-on-wine mx-auto mt-5 max-w-md text-paper/85">
              One formula for that journey—worn, then sealed—until a single
              breath puts you back inside the moment.
            </p>
            <div className="mt-10 flex flex-col items-center gap-6 sm:flex-row sm:justify-center sm:gap-10">
              <Link
                to="/"
                className="cta-parchment inline-flex tracking-wide transition-opacity hover:opacity-90"
              >
                Explore Scentience
              </Link>
              <Link
                to="/the-process"
                className={`${typewriterFaceClass} text-sm font-normal normal-case text-paper/70 underline decoration-paper/35 underline-offset-[6px] transition-colors hover:text-paper hover:decoration-paper/55`}
              >
                How Scent-Mapping works
              </Link>
            </div>
          </div>
        </div>
      </article>

      {/* Related Articles - Style luxueux et réduit */}
      <section className="bg-paper py-16 sm:py-20 border-t border-ink/10">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-lg sm:text-xl lg:text-2xl typo-title text-center mb-10 font-light">
            More Stories
          </h2>
          <div className="grid md:grid-cols-2 gap-8">
            {Object.values(articles)
              .filter((a) => a.id !== article.id)
              .slice(0, 2)
              .map((relatedArticle) => (
                <article
                  key={relatedArticle.id}
                  className="group cursor-pointer"
                  onClick={() =>
                    navigate(getArticlePath(relatedArticle.id))
                  }
                >
                  <div className="flex items-start gap-4">
                    {/* Image réduite */}
                    <div className="flex-shrink-0 w-20 sm:w-24 aspect-[3/4] overflow-hidden">
                      <img
                        src={relatedArticle.heroImage}
                        alt={relatedArticle.title}
                        className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
                      />
                    </div>
                    {/* Content */}
                    <div className="flex-1 min-w-0 space-y-2">
                      <p className="text-[10px] typo-subtitle text-mist font-light">
                        {relatedArticle.category}
                      </p>
                      <h3 className="text-sm sm:text-base typo-title font-light group-hover:text-wine/70 transition-colors leading-tight">
                        {relatedArticle.title}
                      </h3>
                      <p className="text-xs text-ink/70 font-light line-clamp-2 leading-relaxed">
                        {relatedArticle.excerpt}
                      </p>
                    </div>
                  </div>
                </article>
              ))}
          </div>
        </div>
      </section>

      {/* Footer */}
      <SiteFooter />
    </div>
  );
}

/* ---------------- Header ---------------- */
function Header({ navigate }) {
  const [isScrolled, setIsScrolled] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <header
      className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
        isScrolled
          ? "bg-paper/95 backdrop-blur-md border-b border-ink/10"
          : "bg-transparent backdrop-blur-md border-b border-ink/10"
      }`}
    >
      <nav
        className={`max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 ${typewriterFaceClass}`}
      >
        <div className="flex items-center justify-between">
          <button
            onClick={() => navigate("/")}
            className="flex items-center gap-2 text-left"
          >
            <div className="flex flex-col">
              <BrandMark className="text-lg">Scentience</BrandMark>
            </div>
          </button>

          <button
            onClick={() => navigate("/journal")}
            className="text-sm text-mist hover:text-ink transition-colors"
          >
            ← Back to journal
          </button>
        </div>
      </nav>
    </header>
  );
}
